### ISSUE TITLE
Is there a prereq missing?

### ISSUE THREAD

**Issue by seajaysec** [003random/003Recon#14]
I manually installed sublist3r because it wasn't automatically included through the install script, but now I'm running into an error where it seems to fail after Sublist3r runs and then encounters cascading failure.

Any insight into what's tripping it up would be a huge help.

```
→ sudo ./recon.sh DUMMY.SITE
Please read through this script before executing, to prevent unexpected things from happening.
mkdir: DUMMY.SITE: File exists

 -- DUMMY.SITE Started --

                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                # Coded By Ahmed Aboul-Ela - @aboul3la

[-] Enumerating subdomains now for DUMMY.SITE
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
Traceback (most recent call last):
  File "tools/online.py", line 28, in <module>
    input_file_open = open(input_file, 'r')
IOError: [Errno 2] No such file or directory: 'output/DUMMY.SITE/domains-all.txt'

-- Testing crlf on domains in output/DUMMY.SITE/domains.txt with output file, output/DUMMY.SITE/crlf.txt --

tools/crlf.sh: line 15: output/DUMMY.SITE/domains.txt: No such file or directory
tools/crlf.sh: line 15: output/DUMMY.SITE/domains.txt: No such file or directory
tools/crlf.sh: line 15: output/DUMMY.SITE/domains.txt: No such file or directory
tools/crlf.sh: line 15: output/DUMMY.SITE/domains.txt: No such file or directory
tools/crlf.sh: line 15: output/DUMMY.SITE/domains.txt: No such file or directory
tools/crlf.sh: line 15: output/DUMMY.SITE/domains.txt: No such file or directory
tools/crlf.sh: line 15: output/DUMMY.SITE/domains.txt: No such file or directory
tools/crlf.sh: line 15: output/DUMMY.SITE/domains.txt: No such file or directory
tools/crlf.sh: line 15: output/DUMMY.SITE/domains.txt: No such file or directory

-- Done --
-- Scanning for misconfigured cors headers in output/DUMMY.SITE/domains.txt with output file, output/DUMMY.SITE/misconfigured_cors.txt --

[-]File not found!

 -- Done --

-- Testing open redirects on domains in output/DUMMY.SITE/domains.txt with output file, output/DUMMY.SITE/open_redirects.txt --
Traceback (most recent call last):
  File "tools/open_redirect.py", line 48, in <module>
    start()
  File "tools/open_redirect.py", line 17, in start
    domains = open(input_file,'r').read().split('\n')
IOError: [Errno 2] No such file or directory: 'output/DUMMY.SITE/domains.txt'

-- Testing for sensitive info in headers on domains in output/DUMMY.SITE/domains.txt with output file, output/DUMMY.SITE/sensitive_headers.txt --

Traceback (most recent call last):
  File "tools/header_scan.py", line 10, in <module>
    domains = open(input_file,'r').read().split('\n')
IOError: [Errno 2] No such file or directory: 'output/DUMMY.SITE/domains.txt'
Traceback (most recent call last):
  File "tools/error_page_info_check.py", line 10, in <module>
    domains = open(input_file,'r').read().split('\n')
IOError: [Errno 2] No such file or directory: 'output/DUMMY.SITE/domains.txt'
Traceback (most recent call last):
  File "tools/subdomain_takeover_scan.py", line 9, in <module>
    domains = open(input_file,'r').read().split('\n')
IOError: [Errno 2] No such file or directory: 'output/DUMMY.SITE/domains.txt'

-- Extracting javascript files from domains in output/DUMMY.SITE/domains.txt with output file, output/DUMMY.SITE/javascript_files.txt --

Traceback (most recent call last):
  File "tools/javascript_files_extractor.py", line 10, in <module>
    domains_file = open(input_file,'r')
IOError: [Errno 2] No such file or directory: 'output/DUMMY.SITE/domains.txt'

-- Extracting links out of javascript files in output/DUMMY.SITE/javascript_files.txt with output file, output/DUMMY.SITE/extracted_urls.txt  --

[-]File not found!webscreenshot.py version 2.1

Traceback (most recent call last):
  File "dependencies/webscreenshot/webscreenshot.py", line 398, in <module>
    main()
  File "dependencies/webscreenshot/webscreenshot.py", line 391, in main
    url_list = parse_targets(options)
  File "dependencies/webscreenshot/webscreenshot.py", line 227, in parse_targets
    with open(fd,'rb') as fd_input:
IOError: [Errno 2] No such file or directory: 'output/DUMMY.SITE/domains.txt'
Traceback (most recent call last):
  File "tools/wordpress_check.py", line 9, in <module>
    domains = open(input_file,'r').read().split('\n')
IOError: [Errno 2] No such file or directory: 'output/DUMMY.SITE/domains.txt'
[ERROR] cannot load such file -- typhoeus
[TIP] Try to run 'gem install typhoeus' or 'gem install --user-install typhoeus'. If you still get an error, Please see README file or https://github.com/wpscanteam/wpscan

-- Starting a wpscan for the domains in output/DUMMY.SITE/wordpress_sites.txt --

[-]File not found!

 -- Done --

-- Scanning services from output/DUMMY.SITE/domains.txt with output file, output/DUMMY.SITE/nmap_scans.txt --
tools/nmap_scan.sh: line 4: output/DUMMY.SITE/domains.txt: No such file or directory
tools/nmap_scan.sh: line 4: / 1: syntax error: operand expected (error token is "/ 1")
tools/nmap_scan.sh: line 9: output/DUMMY.SITE/domains.txt: No such file or directory
-- Done --

 -- DUMMY.SITE Finished --
```

**Comment by 003random** [comment]
Hey there, @chrsjhnsn,
Have you tried running it with a real domain?
If the domain is invalid, Sublister will not give a output file, which causes the error you described.
003random,

**Comment by 003random** [comment]
Clso
